CC=gcc
WARN=-Wall
FLAG=-lpthread

ALL: SIMPLES CONTA EXERC1 EXERC2

SIMPLES: simples.c
	$(CC) $(WARN) -o simples simples.c $(FLAG)

CONTA: conta.c
	$(CC) $(WARN) -o conta conta.c $(FLAG)

EXERC1: exerc1.c
	$(CC) $(WARN) -o exerc1 exerc1.c $(FLAG)

EXERC2: exerc2.c
	$(CC) $(WARN) -o exerc2 exerc2.c $(FLAG)

.PHONY: ALL
